### ISSUE TITLE
다운로드 폴더에 작품제목이 들어갔으면합니다

### ISSUE THREAD

**Issue by Re0Ma** [Any-Material/waifu-material#1]
다운된 폴더명에 작품명이 들어갔으면 합니다.
태그 저장기능도있었으면해요.

그리고 검색을 하면 가끔 프리징현상이 있습니다.
`Language:krean` 같이 오타를 내도 프리징현상이 납니다.

**Comment by Sombian** [comment]
빠른 시일 내에 추가해 보도록 하겠습니다.
다만 태그 저장 기능이 뭔지 잘 모르겠어서 보다 구현설명을 추가 바랍니다.

**Comment by Re0Ma** [comment]
> > 다운된 폴더명에 작품명이 들어갔으면 합니다.
> > 태그 저장기능도있었으면해요.
> > 그리고 검색을 하면 가끔 프리징현상이 있습니다.
> > `Language:krean` 같이 오타를 내도 프리징현상이 납니다.
> 
> 빠른 시일 내에 추가해 보도록 하겠습니다.
> 다만 태그 저장 기능이 뭔지 잘 모르겠어서 보다 구현설명을 추가 바랍니다.
> 또한 프리징 현상의 경우에는 원인이 확실하게 밝혀지면 수정하도록 하겠습니다.

검색했었던 태그들이 나왔으면 합니다. 혹은 검색했었던 태그들 중 일부를 기억하는 기능있었으면해요
빠른 답변 고맙습니다!

**Comment by Sombian** [comment]
> 
> 
> > > 다운된 폴더명에 작품명이 들어갔으면 합니다.
> > > 태그 저장기능도있었으면해요.
> > > 그리고 검색을 하면 가끔 프리징현상이 있습니다.
> > > `Language:krean` 같이 오타를 내도 프리징현상이 납니다.
> > 
> > 
> > 빠른 시일 내에 추가해 보도록 하겠습니다.
> > 다만 태그 저장 기능이 뭔지 잘 모르겠어서 보다 구현설명을 추가 바랍니다.
> > 또한 프리징 현상의 경우에는 원인이 확실하게 밝혀지면 수정하도록 하겠습니다.
> 
> 검색했었던 태그들이 나왔으면 합니다. 혹은 검색했었던 태그들 중 일부를 기억하는 기능있었으면해요
> 빠른 답변 고맙습니다!

검색에 사용했던 검색어들을 저장해서 재사용 할 수 있도록 추후에 추가해 보겠습니다.
지금까지 사용자분들이 질문만 해놓고 답변이 없는 경우가 99.9% 였기에 마찬가지로 성실한 질문 및 답변 감사합니다...

**Comment by Sombian** [comment]
(`1/2`) 사용자 설정 가능한 폴더명 (승인)
(`2/2`) 태그 기록 재사용 (미승인) // placeholder 로 그전 검색어를 보여줌으로, 불필요하다고 판단.
